server:
  port: 8080

spring:
  application:
    name: workflow
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://123.6.102.119:5432/camunda?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&autoReconnect=true
    username: postgres
    password: 687315e66ae24eeab8bb5c0441a40d79
#  security:
#    oauth2:
#      client:
#        registration:
#          casdoor:
#            client-id: camunda
#            client-secret: camunda
#            scope: read,write
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/login/oauth2/code/custom
#        provider:
#          casdoor:
#            authorization-uri: http://localhost:8000/login/oauth/authorize
#            token-uri: http://localhost:8000/api/login/oauth/access_token
#            user-info-uri: http://localhost:8000/api/get-account
#            user-name-attribute: name
#  security:
#    oauth2:
#      client:
#        registration:
#          oidc:
#            client-id: camunda
#            client-secret: camunda
#            scope: openid, profile, email
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            client-name: OIDC
#        provider:
#          oidc:
#            issuer-uri: http://100.74.79.3:8000/.well-known/openid-configuration

#  security:
#    oauth2:
#      client:
#        registration:
#          oidc:
#            client-id: camunda
#            client-secret: camunda
#            scope: openid, profile, email
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            client-name: OIDC
#        provider:
#          oidc:
#            issuer-uri: http://100.74.79.3:8000/.well-known/openid-configuration
camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
      first-name: demo
      last-name: demo
    database:
      schema-update: true
      type: postgres
    authorization:
      enabled: true
      enabled-for-custom-code: false
    webapp:
      session-cookie:
        enable-secure-cookie: true

casdoor:
  application-name: camunda
  client-id: 0a5975cbaf647a19befa
  client-secret: 21be16dc64c2fdda83dcea16361d5d2dad968fe7
#  endpoint: http://localhost:8000
  endpoint: http://123.6.102.119:8000
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIE1TCCAr2gAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCQxDDAKBgNVBAoTA2p3
    dDEUMBIGA1UEAwwLY2VydF90OTFldnQwHhcNMjQwOTE4MDYxODAzWhcNNDQwOTE4
    MDYxODAzWjAkMQwwCgYDVQQKEwNqd3QxFDASBgNVBAMMC2NlcnRfdDkxZXZ0MIIC
    IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAxRpszZPhglGg0d1w1x2wRUB6
    3dVgWM99MyDiS0jeWigzix5TgRsDfauqBYLQ17BDdF/o36O1PDGuHlcIbf2AbKw5
    rTA9wWTGp/W1DerXAbHbwgw/A/E5UUz2m7wxV20K+oto7JNw0SABlSi3rPO0FXyy
    spr/JGvjErxfKa7STlPRlQdbvfeGB7gwegLqnk1/Kocpk12Gd7fWrHHmfVmY2gnI
    1aFCwBECZPltGJsyyF/ypVXRa4hNpZSbgtPljo1wXPncMmn/MY0M6aojc6GLnwNY
    rkZs4dp22BpHHuHwgRcD9Up/N9kUkyMcicQPh7fI/fLhYnRe3z9grxf8ddoAK4Gs
    lKb0/gmm9cmA1ASMwYrUM6uPPz5451BvmtPLuebt3XqTTYn/P/YTh70Os90CeB8g
    SkjGGChywJTXmAP0BaBRLrKaCce0xTiI9ltYs/0bhf17Y4/T2UVixQxh2JZtHLK1
    UNC+zACjU6erQg5ELS8UIpOL6ix89TB0MnpcQ8cA+AHEhPTRUGNLxoNCbAXFx7bc
    4Dn/HpT/dv4eDyR3RAkOuX0wQMsXj3UOJ8UXjpc/+RbBcG2uu66Bp1+9hRzT5SDq
    TGt1I1FE16Exs5Z50j1Ou6844KnMxO6P2v8bg3JbFxM8puuAzSVm7RUUFME/Rzsu
    Bxlol2s6uJ8bUfyJraUCAwEAAaMQMA4wDAYDVR0TAQH/BAIwADANBgkqhkiG9w0B
    AQsFAAOCAgEAo47TJlBhOixc1HF52PoNoTDooQGCbJBZfiBUABkCBH97Y4UQdlwv
    EjArd5106zhQURlxWe1ZONyBUtffn5UFQLN2UjmiMXR4zZTyFQIYrglYJcbuGD1j
    pEdGDSqINi0+r58zBzdLaAwM/Ot8dBBzW3FPJgxn81WmcSC58DkkFrsjU/4qeb3J
    rihAl+dHLDg1w5dWVNBbsgPjbFnQVuRD/CI6cfmi23asK2fWUsCzhUjEK4Kn+B/u
    xwsL22OAdyEyuGaV+RV9MXI/52DlvklxRxQkXG5GvdqXB/Tsq+HEj92+/K/gGA0a
    BREXzCr6fO77Kvb+y2aDt+05d7r58WNagG6uPmGxmyWLS+1jof61QAuoMVVeoUgb
    N7Kk8iCE3xmebNSXvcYZqFiQ4RrGgz6QRKFGg0vGUR/aKpkfm20PY8cjUY5n3u41
    LX6HtoXLh9BFqV/wYrbbPj6fFT6cH9h0NmnO33QwU+8a3mamOuhGuBJnbAVjBwTm
    JIRcb5w4HlVsAATce46JbbPUfyjt5uoncV+GNmQnGS+Dg3epvpd6rD42oevvDAl5
    9oBhU+xMM3TY1PdbVUUgfZXfkFeK6sE2msd6L7xKHJ1lu5EXOQD+M0YW/iqAPPQN
    qetuxljzNKcTpGrefgt20Y6tv/Ir5PTOm4xJxeZ2PhVwUuPde8XP7EQ=
    -----END CERTIFICATE-----
  organization-name: jwt
#logging:
#  level:
#     org.camunda.bpm: DEBUG
#     org.camunda.bpm.engine: DEBUG
#     org.camunda.bpm.engine.impl: DEBUG

# swagger ui 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    urls:
      - url: http://localhost:8080/openapi.json
        name: camunda
      - url: http://localhost:8080/v3/api-docs
        name: customize
  api-docs:
    path: /v3/api-docs
    enabled: true
logging:
  config: classpath:logback.xml
  level:
    org.camunda: DEBUG