global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['127.0.0.1:9093']

#rule_files:
#  - "node_down.yml"

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']


  - job_name: 'node'
    scrape_interval: 8s
    static_configs:
      - targets: ['prometheus-node-exporter:9100']
  # mysql-exporter
  - job_name: 'mysql-exporter'
    scrape_interval: 8s
    metrics_path: /metrics
    static_configs:
      - targets: ['mysql-exporter:9104']
  - job_name: 'postgres-exporter'
    scrape_interval: 8s
    metrics_path: /metrics
    static_configs:
      - targets: ['pgsql-exporter:9187']