version: '3.0'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
    volumes:
      # 数据存放位置
      - ./mysql/data/:/var/lib/mysql/
      # 配置
      - ./mysql/conf/:/etc/mysql/conf.d/
      # 初始化sql脚本存放位置
      - ./mysql/init/:/docker-entrypoint-initdb.d/
    networks:
      - basics

  postgres:
    image: postgres:alpine3.19
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Shanghai
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data/
      - ./postgres/conf/:/etc/postgresql/
      - ./postgres/init/:/docker-entrypoint-initdb.d/
    networks:
      - basics

  redis:
    image: redis
    container_name: redis
    ports:
      - "6399:6379"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - REDIS_PASSWORD=123456
    volumes:
      - ./redis/data/:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/log/:/usr/local/etc/redis/log
    command: redis-server /usr/local/etc/redis/redis.conf

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - ./mongo/data/:/data/db
      - ./mongo/conf/:/data/configdb/
      - ./mongo/log/:/data/log/
      - ./mongo/init/:/docker-entrypoint-initdb.d/

# 依赖已经创建好的网络
networks:
  basics:
    external: true
