# 服务监控相关的服务
version: '3.0'
services:
  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./prometheus/data/:/prometheus
      - ./prometheus/conf/prometheus.yml/:/etc/prometheus/prometheus.yml
      - ./prometheus/logs/:/var/log/prometheus/
      - ./prometheus/rules/:/etc/prometheus/rules/
    depends_on:
      - grafana
      - prometheus-node-exporter
    networks:
      - basics

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/data/:/var/lib/grafana
      - ./grafana/logs/:/var/log/grafana
    networks:
      - basics

  prometheus-node-exporter:
    image: prom/node-exporter:master
    container_name: prometheus-node-exporter
    ports:
      - "9100:9100"
    restart: always
    networks:
      - basics

  # loki
  loki:
    image: grafana/loki:main-f6f8bab
    container_name: loki
    ports:
      - "3100:3100" # Loki的HTTP接口
      - "9095:9095" # Loki的gRPC接口，用于Promtail
    volumes:
      - ./loki/data:/var/loki
      - ./loki/config/local-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    depends_on:
      - grafana
    networks:
      - basics

  #  promtail loki的日志收集器
  promtail:
    image: grafana/promtail:main
    container_name: promtail
    volumes:
      - ./promtail/log:/var/log
      - ./promtail/config/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - basics


# 依赖已经创建好的网络
networks:
  basics:
    external: true
